packages:
  - apps/*
  - packages/**
  - tooling/*
catalog:
  "@babel/core": ^7.26.0
  "@expo/vector-icons": ^15.0.2
  "@gorhom/bottom-sheet": ^5.2.6,
  "@hookform/resolvers": ^3.9.1
  "@manypkg/cli": ^0.23.0
  "@react-native-async-storage/async-storage": 2.2.0
  "@react-navigation/drawer": ^7.5.10
  "@react-navigation/native": ^7.0.14
  "@rn-primitives/accordion": ^1.1.0
  "@rn-primitives/alert-dialog": ^1.1.0
  "@rn-primitives/avatar": ^1.1.0
  "@rn-primitives/checkbox": ^1.1.0
  "@rn-primitives/collapsible": ^1.1.0
  "@rn-primitives/dialog": ^1.1.0
  "@rn-primitives/dropdown-menu": ^1.1.0
  "@rn-primitives/hover-card": ^1.1.0
  "@rn-primitives/label": ^1.1.0
  "@rn-primitives/menubar": ^1.1.0
  "@rn-primitives/navigation-menu": ^1.1.0
  "@rn-primitives/popover": ^1.1.0
  "@rn-primitives/progress": ^1.1.0
  "@rn-primitives/radio-group": ^1.1.0
  "@rn-primitives/select": ^1.1.0
  "@rn-primitives/separator": ^1.1.0
  "@rn-primitives/slot": ^1.1.0
  "@rn-primitives/switch": ^1.1.0
  "@rn-primitives/table": ^1.1.0
  "@rn-primitives/tabs": ^1.1.0
  "@rn-primitives/toggle": ^1.1.0
  "@rn-primitives/toggle-group": ^1.1.0
  "@rn-primitives/types": ^1.1.0
  "@shopify/flash-list": 2.0.2
  "@supabase/supabase-js": ^2.52.0
  "@tanstack/react-query": ^5.62.16
  "@trivago/prettier-plugin-sort-imports": ^5.2.1
  "@turbo/gen": ^2.3.3
  "@types/aes-js": ^3.1.4
  "@types/eslint": ^8.56.5
  "@types/jest": ^30.0.0
  "@types/node": ^22.7.5
  "@types/react": ~19.1.10
  "@types/react-dom": ^18.3.1
  "@types/react-test-renderer": 18.0.7
  "@typescript-eslint/eslint-plugin": ^8.19.1
  "@typescript-eslint/parser": ^8.19.1
  "@vercel/style-guide": ^5.2.0
  aes-js: ^3.1.2
  babel-plugin-module-resolver: 5.0.2
  class-variance-authority: ^0.7.0
  clsx: ^2.1.1
  cross-env: ^7.0.3
  eslint: 8.57.0
  eslint-config-expo: ~10.0.0
  eslint-config-prettier: ^9.1.0
  eslint-config-turbo: ^2.3.3
  eslint-plugin-only-warn: ^1.1.0
  expo: ~54.0.10
  expo-auth-session: ^5.5.2
  expo-constants: ~18.0.9
  expo-dev-client: ~6.0.12
  expo-document-picker: ^13.0.1
  expo-font: ~14.0.8
  expo-linking: ~8.0.8
  expo-router: ~6.0.8
  expo-secure-store: ^14.0.0
  expo-splash-screen: ~31.0.10
  expo-status-bar: ~3.0.8
  expo-system-ui: ~6.0.7
  expo-web-browser: ~15.0.7
  expo-haptics: ~15.0.7
  expo-image: ~3.0.9
  expo-linear-gradient: ~15.0.7
  jest: ^30.2.0
  jest-expo: ~54.0.12
  lucide-react-native: ^0.544.0
  metro-cache: ^0.83.3
  nativewind: 4.2.1
  prettier: ^3.4.2
  prettier-plugin-tailwindcss: ^0.6.8
  react: 19.1.0
  react-dom: 19.1.0
  react-hook-form: ^7.54.2
  react-is: 18.3.1
  react-native: 0.81.4
  react-native-gesture-handler: ~2.28.0
  react-native-get-random-values: ^1.11.0
  react-native-reanimated: ~4.1.0
  react-native-safe-area-context: ~5.6.0
  react-native-screens: ~4.16.0
  react-native-svg: 15.12.1
  react-native-ui-lib: ^7.46.3
  react-native-web: ~0.21.0
  react-native-worklets: 0.5.1
  react-native-keyboard-controller: 1.18.5
  react-test-renderer: 19.1.0
  supabase: 2.51.0
  sonner: 1.7.2
  sonner-native: 0.16.2
  tailwind-merge: ^2.6.0
  tailwindcss: ^3.4.17
  tailwindcss-animate: ^1.0.7
  turbo: ^2.3.3
  typescript: ~5.9.2
  zod: ^3.24.1
  zustand: ^5.0.8
  react-native-mmkv: ^3.3.3
