create table "public"."help_center" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "created_by" uuid,
    "question" text not null,
    "status" report_status not null default 'pending'::report_status
);


alter table "public"."help_center" enable row level security;

alter table "public"."user_preferences" alter column "show_sensitive_content" set default true;

CREATE UNIQUE INDEX "help center_pkey" ON public.help_center USING btree (id);

alter table "public"."help_center" add constraint "help center_pkey" PRIMARY KEY using index "help center_pkey";

alter table "public"."help_center" add constraint "help center_created_by_fkey" FOREIGN KEY (created_by) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."help_center" validate constraint "help center_created_by_fkey";

grant delete on table "public"."help_center" to "anon";

grant insert on table "public"."help_center" to "anon";

grant references on table "public"."help_center" to "anon";

grant select on table "public"."help_center" to "anon";

grant trigger on table "public"."help_center" to "anon";

grant truncate on table "public"."help_center" to "anon";

grant update on table "public"."help_center" to "anon";

grant delete on table "public"."help_center" to "authenticated";

grant insert on table "public"."help_center" to "authenticated";

grant references on table "public"."help_center" to "authenticated";

grant select on table "public"."help_center" to "authenticated";

grant trigger on table "public"."help_center" to "authenticated";

grant truncate on table "public"."help_center" to "authenticated";

grant update on table "public"."help_center" to "authenticated";

grant delete on table "public"."help_center" to "service_role";

grant insert on table "public"."help_center" to "service_role";

grant references on table "public"."help_center" to "service_role";

grant select on table "public"."help_center" to "service_role";

grant trigger on table "public"."help_center" to "service_role";

grant truncate on table "public"."help_center" to "service_role";

grant update on table "public"."help_center" to "service_role";



create policy "Enable insert for authenticated users only"
on "public"."help_center"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable users to view their own data only"
on "public"."help_center"
as permissive
for select
to authenticated
using ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.supabase_user = auth.uid()) AND (profiles.id = help_center.created_by)))));


CREATE TRIGGER tr_help_center_autoset_created_by BEFORE INSERT ON public.help_center FOR EACH ROW EXECUTE FUNCTION set_created_by_value();



